---
- name: "Create podman systemd service"
  ansible.builtin.template:
    src: "{{ 'pod.service.j2' if podman_systemd_service_type == 'pod' else 'container.service.j2' }}"
    dest: "/etc/systemd/system/{{ podman_systemd_service_name }}.service"
    owner: "root"
    group: "root"
    mode: "0644"
- name: "Add pod service override directory"
  ansible.builtin.file:
    dest: "/etc/systemd/system/{{ podman_container_pod }}.service.d"
    owner: "root"
    group: "root"
    mode: "0755"
    state: directory
  when: podman_systemd_service_type == "container"
- name: "Add dependency in pod service"
  ansible.builtin.template:
    src: "override.conf.j2"
    dest: "/etc/systemd/system/{{ podman_container_pod }}.service.d/override.conf"
    owner: root
    group: root
    mode: "0644"
  when: podman_systemd_service_type == "container"
- name: "Reload systemd configuration"
  ansible.builtin.systemd:
    daemon_reload: true
