---
- name: "Remove vector examples"
  ansible.builtin.file:
    dest: "/etc/vector/examples"
    state: "absent"
- name: "Create vector configuration dir"
  ansible.builtin.file:
    state: "directory"
    dest: "/etc/vector/{{ __vector_conf_dir }}"
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - "sources"
    - "transforms"
    - "sinks"
  loop_control:
    loop_var: "__vector_conf_dir"
- name: "Create vector configuration"
  ansible.builtin.copy:
    src: "{{ __vector_conf.src }}"
    dest: "{{ __vector_conf.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - src: "vector"
      dest: "/etc/default/vector"
    - src: "vector.yaml"
      dest: "/etc/vector/vector.yaml"
  loop_control:
    loop_var: "__vector_conf"
