---
- name: Create podman systemd service
  ansible.builtin.template:
    src: "{{ 'pod.service.j2' if systemd_service_type == 'pod' else 'container.service.j2' }}"
    dest: "/etc/systemd/system/{{ systemd_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
- name: Add pod service override directory
  ansible.builtin.file:
    state: directory
    dest: "/etc/systemd/system/{{ container_pod }}.service.d"
    owner: root
    group: root
    mode: "0755"
  when: systemd_service_type == "container"
- name: Add dependency in pod service
  lineinfile:
    path: "/etc/systemd/system/{{ container_pod }}.service.d/override.conf"
    line: "{{ dependency_item }}"
    owner: root
    group: root
    mode: "0644"
    create: true
  loop:
    - "Requires={{ systemd_service_name }}.service"
    - "Before={{ systemd_service_name }}.service"
  loop_control:
    loop_var: dependency_item
  when: systemd_service_type == "container"
- name: Reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: true
