---
- name: "Get podman container info"
  containers.podman.podman_container_info:
    name: "{{ podman_container_name }}"
  register: "__podman_container_info"
- name: "Get podman volume info"
  containers.podman.podman_volume_info:
    name: "{{ container_volume_item.Name }}"
  register: "__podman_container_volume_info"
  loop: "{{ __podman_container_info.containers[0].Mounts if __podman_container_info.containers[0] is defined else [] }}"
  loop_control:
    loop_var: "__podman_container_volume_item"
    label: "{{ __podman_container_volume_item.Name }}"
- name: "Destroy podman container"
  containers.podman.podman_container:
    state: "absent"
    name: "{{ container_name }}"
- name: "Destroy podman secret"
  ansible.builtin.include_role:
    name: podman_secret
    tasks_from: "absent"
  vars:
    secret_name: "{{ __podman_container_secret_item }}"
  loop: "{{ lookup('template', 'absent-secrets.yaml.j2') | from_yaml }}"
  loop_control:
    loop_var: __podman_container_secret_item
- name: Destroy podman volume
  ansible.builtin.include_role:
    name: podman_volume
    tasks_from: absent
  vars:
    volume_name: "{{ volume_item.name }}"
    volume_type: "{{ volume_item.type }}"
  loop: "{{ lookup('template', 'absent-volumes.yaml.j2') | from_yaml }}"
  loop_control:
    loop_var: volume_item
  when: remove_volumes is true
- name: "Destroy podman container systemd service"
  ansible.builtin.include_role:
    name: podman_systemd_service
    tasks_from: "absent"
  vars:
    podman_systemd_service_name: "{{ podman_container_name }}"
    podman_systemd_service_type: "container"
