---
- name: "Ensure Podman is installed"
  ansible.builtin.dnf:
    name:
      - "podman"
      - "podman-docker"
      - "skopeo"
      - "crun"
      - "fuse-overlayfs"
      - "containernetworking-plugins"
    state: "{{ podman_packages_state }}"
