---
argument_specs:
  main:
    short_description: Generate deployment id
    options:
      env:
        type: str
        required: true
        description: Environment
      service_name:
        type: str
        required: true
        description: Service name
