---
argument_specs:
  present:
    short_description: Create podman container
    options:
      podman_container_name:
        type: str
        required: true
        description: Container name
      podman_container_pod:
        type: str
        required: false
        description: Container pod name
      podman_container_image:
        type: str
        required: true
        description: Container image
      podman_container_command:
        type: raw
        required: false
        description: Container command
      podman_container_catatonit:
        type: bool
        required: true
        description: Container catatonit use
      podman_container_secrets:
        type: list
        elements: dict
        required: false
        description: List of container secrets
      podman_container_volumes:
        type: list
        elements: dict
        required: false
        description: List of container volumes
      podman_container_network:
        type: str
        required: false
        description: Container network
      podman_container_publis:
        type: list
        elements: str
        required: false
        description: List of container ports
  absent:
    short_description: Destroy podman Container
    options:
      podman_container_name:
        type: str
        required: true
        description: Container name
      remove_volumes:
        type: bool
        required: true
        description: Destroy volumes with container
  started:
    short_description: Start podman Container
    options:
      podman_container_name:
        type: str
        required: true
        description: Container name
  stopped:
    short_description: Stop podman Container
    options:
      podman_container_name:
        type: str
        required: true
        description: Container name
