---
- name: "Destroy podman pod"
  containers.podman.podman_pod:
    state: "absent"
    name: "{{ podman_pod_name }}"
- name: "Destroy podman pod systemd service"
  ansible.builtin.include_role:
    name: podman_systemd_service
    tasks_from: "absent"
  vars:
    podman_systemd_service_name: "{{ podman_pod_name }}"
    podman_systemd_service_type: "pod"
