---
- name: "Create podman pod"
  containers.podman.podman_pod:
    name: "{{ podman_pod_name }}"
    state: "created"
    infra_name: "{{ podman_pod_name + '-infra' }}"
    infra_conmon_pidfile: "/run/containers/pids/{{ podman_pod_name + '-infra' }}.pid"
    network: "{{ podman_pod_network }}"
    publish: "{{ podman_pod_publish if podman_pod_publish is defined else [] }}"
- name: "Create podman pod systemd service"
  ansible.builtin.include_role:
    name: podman_systemd_service
    tasks_from: "present"
  vars:
    podman_systemd_service_name: "{{ podman_pod_name }}"
    podman_systemd_service_type: "pod"
