---
- name: "Create vector sink configuration"
  ansible.builtin.template:
    src: "prometheus.yaml.j2"
    dest: "/etc/vector/sinks/prometheus.yaml"
    owner: "root"
    group: "root"
    mode: "0644"
