---
- name: "Check volume type"
  ansible.builtin.fail:
    msg: "Allowed volume types are: 'local', 'zfs' or 's3'"
  when: >
    (podman_volume_type != "local") and
    (podman_volume_type != "zfs") and
    (podman_volume_type != "s3")
- name: "Create volume"
  ansible.builtin.include_tasks: "present-{{ podman_volume_type }}.yaml"
