---
- name: "Ensure Osquery is installed"
  ansible.builtin.dnf:
    name:
      - "osquery"
    state: "{{ osquery_packages_state }}"
#TODO: check osqueryd service state and stop if running
- name: "Remove osquery data directory in /var"
  ansible.builtin.file:
    dest: "/var/osquery"
    state: "absent"
- name: "Create osquery data directory in /var/lib"
  ansible.builtin.file:
    dest: "/var/lib/osquery"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
