---
argument_specs:
  present:
    short_description: Create podman systemd service
    options:
      podman_systemd_service_name:
        type: str
        required: true
        description: Systemd service name
      podman_systemd_service_type:
        type: str
        required: true
        description: Systemd service type
      podman_pod_name:
        type: str
        # `required` should be true but since I can't have mutualy exlusive args here we are
        # but if this is not defined at this point something bad already happened
        required: false
        description: Podman pod name for pod template
      podman_container_name:
        type: str
        # same as above
        required: false
        description: Podman container name for container template
      podman_container_pod:
        type: str
        # same as above
        required: false
        description: Podman pod name for container template
  absent:
    short_description: Destroy podman systemd service
    options:
      podman_systemd_service_name:
        type: str
        required: true
        description: Systemd service name
  started:
    short_description: Start podman systemd service
    options:
      podman_systemd_service_name:
        type: str
        required: true
        description: Systemd service name
  stopped:
    short_description: Stop podman systemd service
    options:
      podman_systemd_service_name:
        type: str
        required: true
        description: Systemd service name
