---
- hosts: rhel7
  gather_facts: false
  tasks:
    - name: "Update rpm"
      ansible.builtin.yum:
        name:
          - "rpm"
        state: "latest"
    - name: "Update yum"
      ansible.builtin.yum:
        name:
          - "yum"
        state: "latest"
    - name: "Update all"
      ansible.builtin.yum:
        name:
          - "*"
        exclude:
          - "kernel*"
          - "kmod*"
          - "libnvpair*"
          - "libuutil*"
          - "libzfs*"
          - "libzpool*"
          - "zfs*"
        state: "latest"
- hosts: rhel8,rhel9
  gather_facts: false
  tasks:
    - name: "Update rpm"
      ansible.builtin.dnf:
        name:
          - "rpm"
        state: "latest"
    - name: "Update dnf"
      ansible.builtin.dnf:
        name:
          - "dnf"
        state: "latest"
    - name: "Update all"
      ansible.builtin.dnf:
        name:
          - "*"
        exclude:
          - "kernel*"
          - "kmod*"
          - "libnvpair*"
          - "libuutil*"
          - "libzfs*"
          - "libzpool*"
          - "zfs*"
        state: "latest"
