---
- hosts: all
  gather_facts: false
  tasks:
    - name: "Install Podman"
      ansible.builtin.include_role:
        name: podman
      vars:
        podman_storage_driver: "zfs"
        podman_log_driver: "journald"
        podman_network_backend: "cni"
        podman_default_network: "mesh-internal"
        podman_compression_format: "zstd"
        podman_volume_path: "/var/lib/volumes"
        podman_cni_subnet: "{{ cni_subnet }}"
        podman_oci_registry: "{{ oci_registry_url }}"